services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    networks:
      - wp_network
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
      - redis


  db:
    image: mysql:5.7
    container_name: wordpress_db
    networks:
      - wp_network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wp_database
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - wp_network
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: wordpress_redis
    networks:
      - wp_network
    ports:
      - "6379:6379"
    command: [ "redis-server"]
    volumes:
      - redis_data:/data

networks:
  wp_network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
  redis_data: